##########################
# This is assignment 1 Makefile
############################

CC						= gcc
CFLAGS				= -O2 -fopenmp

mosaic: mosaic.c
	$(CC) mosaic.c -o mosaic $(CFLAGS)

clean:
	rm -rf *.o
